### ISSUE TITLE
bundle : displacement of circle label

### ISSUE THREAD

**Issue by roscha** [d3/d3#3000]
Hi, 

I think it's a small issue/question that I propose, I am using the bundle visualization. as label, I use "-" and I changed the css style as such:

```css
.node {
  font: 300 11px "Helvetica Neue", Helvetica, Arial, sans-serif;
  fill: #bbb;
  
  font-size: 36px;
  font-weight: bold;
  line-height: 26.4px;
}
```

mainly to have a nice and big "-"

but I observe a little displacement of the circle label, like the diameter of the label circle position and angle is not exactly define the same way on each side of the wheel. 
So I see that half way, the label are reversed but I don't see how this could produce this artifact. May be someone encounter the issue already

see figure https://1drv.ms/f/s!ApPwUjpLIL5sioEkiYbnMcUjASQ1kg
especially at the bottom it's visible

hope you have a clue about that :)
Roselyne
